// import './globals.css'
import "csscss"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/csscss@latest/index.css" />
      </head>
      <body className="ma-0 tx-sans">{children}</body>
    </html>
  )
}
